### ISSUE TITLE
Scanpy notebook not available

### ISSUE THREAD

**Issue by MSMortensen** [cellgeni/notebooks#18]
Hi,

The scanpy notebook listed on the frontpage is missing.
Can this please be made available again?

Kind regards,
Martin

**Comment by prete** [comment]
Hi @MSMortensen, notebook was taken down as it's being reworked but you can access the old one here:
https://github.com/cellgeni/notebooks/blob/33f6d5317bd7a05f70157a9ad5c1e3435734924f/notebooks/10X-scanpy.ipynb
